### ISSUE TITLE
RotFM migration

### ISSUE THREAD

**Issue by itteerde** [itteerde/fvttconfig#194]
RotFM migration. This is actually doing the migration. The testing and fixing is somewhere else.

- [x] backup.
- [x] update System (from manually provided manifest url!).
- [x] update all Modules (there should be an expected list provided @itteerde ).
- [x] F-12, launch World, patience. Create Issues for unexpected.
- [x] `itemacro` Configuration, enable `Override default macro execution`.
- [x] `dnd5e` Configuration, switch Encumbrance Tracking to `Variant (...)`
- [x] turn Monk's Spells Prepration monitoring back on if you like @PhDaveMil .
- [x] show how to correctly setup a `Spell Item` `ActiveEffect` now to @PhDaveMil . Maybe @Taseabridge wants to edit the wiki page accordingly?
- [x] show AE handling via ChatMessage to @PhDaveMil  and test with him.
- [x] run DDBImporter munching (with F-12).
- [x] sanity-check DDB-Compendia.
- [x] import an Actor via DDBImporter.
- [x] install [effectivetray](https://github.com/etiquettestartshere/effectivetray) #212 .
- [x] correct Gial's AEs #203 .
- [x] fix Herja #204 .
- [x] fix Ezo #205 .
- [x] fix Ketris #206 .
- [x] fix Kythos #207 .
- [x] fix Sol #208 .
- [x] test Arcane Recovery, #181.
- [x] test Hide, #171.
- [ ] test and fix used `Macros` #210 .
- [ ] test Combat with three Players, PCs, NPCs and multiple Rounds, including killing Participants, Summon X, fixing Summon Initiative.

**Comment by itteerde** [comment]
![image](https://github.com/itteerde/fvttconfig/assets/8367477/647d4031-8e70-42a3-90b6-00f218547789)

**Comment by itteerde** [comment]
continue with Charcter munching (Feats, Subclasses, incl. experimental)
