### ISSUE TITLE
Test used Macros

### ISSUE THREAD

**Issue by itteerde** [itteerde/fvttconfig#210]
Test used Macros

- [x] test `Cycle Wildcard Token` `Macro`.
- [x] test `Cycle Wildcard Token` `Macro -1`.
- [x] test `Report` `Macro`.
- [x] test `Secret` (`disposition`) `Macro` #185 .
- [x] test `Friendly` (`disposition`) `Macro` #185 .
- [x] test `Hostile` (`disposition`) `Macro` #185 .
- [x] test `Neutral` (`disposition`) `Macro` #185 .
- [x] test `Torch` `Macro` (replace with repo version [not in Compendium yet]) #182 .
- [ ] test `-10hp` `Macro`.
- [ ] test `-1hp` `Macro`.
- [ ] test `-5hp` `Macro`.
- [ ] test `+10hp` `Macro`.
- [ ] test `+5hp` `Macro`.
- [ ] test `+1hp` `Macro`.
- [x] test `dim Down` `Macro`.
- [x] test `dim Up` `Macro`.
- [x] test `Rotate CCW -1` `Macro`.
- [x] test `Rotate CCW -45` `Macro`.
- [x] test `Rotate CW +1` `Macro`.
- [x] test `Rotate CW +45` `Macro`.
- [x] test `ScaleDown` `Macro`.
- [x] test `ScaleUp` `Macro`.
- [ ] test `tHP -1` `Macro`.
- [ ] test `tHP -10` `Macro`.
- [ ] test `tHP +1` `Macro`.
- [ ] test `tHP +10` `Macro`.
- [x] test `Timeout` `Macro`.
- [ ] test `Update Initiative` `Macro` #214 .
- [x] test `Volume Save` `Macro`.

**Comment by itteerde** [comment]
migration done. should clean up compendizm though -- for which there is another issue.
